name: Check Permission Changes

on:
  push:
    branches:
      - main  # change this to the branch you want to trigger the workflow
  pull_request:
    branches:
      - main # Same as above

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
      
    - name: Check for yml changes
      id: files
      run: |
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'permissions/*.yml' | xargs echo)
        if [[ -z "$FILES" ]]; then
          echo "No changes detected in permissions files."
        else
          echo "Changes detected. Processing..."
          java -jar target/github_team_sync.jar $FILES
        fi
      env:
        ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
